config/routes.rb
Openspace::Application.routes.draw do
  #omniauth
  match "/auth/:provider/callback" => "authentication#create"
  match "/signout" => "authentication#destroy", :as => :signout

  resources :users
  
  resources :events do
    member do
      get 'menu'
      get 'tweets'
      post 'restart_voting'
    end
    
    resources :agenda
    resources :locations
    resources :slots

    resources :sessions do 
      resources :votes
    end
  end
    
  #navigation
  match "/openspace" => "navigation#openspace"
  match "/about" => "navigation#about"
  
  root :to => 'navigation#index'

end

app/models/user.rb
# Usuario del Open Space
class User < ActiveRecord::Base
  attr_accessible :provider, :uid, :name, :nickname, :role
  ROLES = %w[admin assistant].freeze
  has_many :sessions
  validates_inclusion_of :role, :in => ROLES
  validates_presence_of :provider, :uid, :name, :nickname
    
  # OAuth para Facebook y Twitter
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.nickname = auth["info"]["nickname"]
      user.role = 'assistant'
    end
  end
  
  def admin?
    role == 'admin'
  end

  def assistant?
    role == 'assistant'
  end

  # Votar por una sesion en un evento
  def vote(event, session)
    # TODO pasar el 3 a un atributo del evento configurable
    if self.assistant? and self.votes_count(event) >= 3
      raise "Tienes un maximo de 3 votos"
    end
    Vote.create(event: event, session: session, user: self)
  end

  # Numero de votos que ha realizado el usuario en el evento
  def votes_count(event)
    Vote.where(event_id: event.id, user_id: self.id).count
  end

  def promote_to_admin
    self.role = 'admin'
    self
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'El usuario fue creado satisfactoriamente.'
    else
      render action: "new"        
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'El usuario fue actualizado satisfactoriamente.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :nickname %><%= f.text_field :nickname, :disabled => true %>
  <%= f.label :role %><%= f.select(:role, User::ROLES) %>
  
  <fieldset class="ui-grid-a">
  		<div class="ui-block-a"><%= f.submit 'Guardar', 'data-icon'=>'check', 'data-theme'=>'b' %></div>
  		<div class="ui-block-b"><%= link_to 'Cancelar', users_path, 'data-role'=>'button', 'data-icon'=>'back' %></div>
  </fieldset>
  
<% end %>

app/views/users/edit.html.erb
<%= content_for :header do %>
  <%= link_to "", users_path, 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Editar</h1>
<% end %>

<%= render 'form' %>

app/views/users/index.html.erb
<%= content_for :header do %>
  <%= link_to_home %>
  <h1>Usuarios</h1>
<% end %>

<ul data-role="listview" data-filter="true" data-inset="true">
  <% @users.each do |user| %>
    <li><%= link_to "#{user.nickname} (#{user.role})", user_path(user) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= content_for :header do %>
  <%= link_to "", users_path, 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Usuario</h1>
  <%= link_to "Editar", edit_user_path(@user) %>
<% end %>

Usuario: <%= @user.nickname %><br />
Rol: <%= @user.role %>