config/routes.rb
Openspace::Application.routes.draw do
  #omniauth
  match "/auth/:provider/callback" => "authentication#create"
  match "/signout" => "authentication#destroy", :as => :signout

  resources :users
  
  resources :events do
    member do
      get 'menu'
      get 'tweets'
      post 'restart_voting'
    end
    
    resources :agenda
    resources :locations
    resources :slots

    resources :sessions do 
      resources :votes
    end
  end
    
  #navigation
  match "/openspace" => "navigation#openspace"
  match "/about" => "navigation#about"
  
  root :to => 'navigation#index'

end

app/models/event.rb
# Evento del Open Space
class Event < ActiveRecord::Base
  attr_accessible :name, :description, :starting_at, :ending_at, :where, :website, :hashtag, :latitude, :longitude
  has_many :sessions
  has_many :locations
  has_many :agendas
  validates_presence_of :name
  
  # SEO Friendly URLs
  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.current_events
    Event.where("status != 'ended'")
  end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  skip_authorization_check :only => [:menu, :tweets]

  def menu
    event = Event.find(params[:id])
    session[:event_id] = event.id
  end

  def tweets
    #TODO implementar cache
    @tweets = Twitter.search(current_event.hashtag).map{ |t| "#{t.from_user}: #{t.text}" }
  end

  def restart_voting
    @event = Event.find(params[:id])
    Vote.delete_all(event_id: @event.id)
    Session.where(event_id: @event.id).update_all(votes_count: 0)
    redirect_to @event
  end
  
  def index
    @events = Event.all
  end

  def voting 
    @sessions = Session.where(event_id: current_event.id).order(:title)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
    session[:event_id] = @event.id
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to @event
    else
      render action: "new"
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event
    else
      render action: "edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :name %><%= f.text_field :name, :placeholder => 'Nombre el evento' %>
  <fieldset data-role="controlgroup" data-type="horizontal">
    <legend>Cuando</legend>
    <%= f.date_select :starting_at %>
  </fieldset>
  <fieldset data-role="controlgroup" data-type="horizontal">
    <legend>Hora inicio</legend>
    <%= f.time_select :starting_at %>
  </fieldset>
  <fieldset data-role="controlgroup" data-type="horizontal">
    <legend>Hora fin</legend>
    <%= f.time_select :ending_at %>
  </fieldset>
  <%= f.label :where %><%= f.text_field :where, :placeholder => 'Lugar del evento' %>
  <%= f.label :description %><%= f.text_area :description, :placeholder => 'Descripción del evento' %>
  <%= f.label :website %><%= f.text_field :website, :placeholder => 'Website del evento' %>
  <%= f.label :hashtag %><%= f.text_field :hashtag, :placeholder => 'Twitter Hashtag' %>
  <%= f.label :description %><%= f.text_area :description, :placeholder => 'Descripción del evento' %>

  <% unless @event.new_record? %>
    <%= link_to "Nuevo ambiente", new_event_location_path(@event), 'data-role'=>'button' %>

    <ul data-role="listview" data-inset="true">
      <li data-role="list-divider">Ambientes</li>
        <% @event.locations.each do |location| %>
          <li><%= link_to location.name, edit_event_location_path(@event, location) %></li>
        <% end %>
    </ul>
  <% end %>
  
  <fieldset class="ui-grid-a">
  		<div class="ui-block-a"><%= f.submit 'Guardar', 'data-theme'=>'b' %></div>
  		<div class="ui-block-b"><%= link_to 'Cancelar', event_path(current_event), 'data-role'=>'button' %></div>
  </fieldset>
<% end %>

app/views/events/agenda.html.erb
<%= content_for :header do %>
  <%= link_to "Evento", menu_event_path(current_event), 'data-icon'=> 'back' %>
  <h1>Agenda</h1>
<% end %>

<ul data-role="listview" data-inset="true">
  <% @agenda.each do |item| %>
    <li data-role="list-divider"><%= item.starts.strftime('%H:%M') %> - <%= item.ends.strftime('%H:%M') %></li>
    <li>
      <h3><%= item.title %></h3>
      <p>
        <%= item.slots.map { |f| f.location.name }.join ', ' %>
      </p>
    </li>
  <% end %>
</ul>

app/views/events/edit.html.erb
<%= content_for :header do %><h1>Editar evento</h1><% end %>
<%= button_to "Reiniciar votación", restart_voting_event_path(current_event), 'data-role'=>'button' %>

<%= render 'form' %>

app/views/events/index.html.erb
<%= content_for :header do %>
  <%= link_to_home %>
  <h1>Eventos</h1>
  <%= link_to "Nuevo", new_event_path if can? :create, Event %>
<% end %>

<ul data-role="listview" data-inset="true" data-filter="true">
<% @events.each do |event| %>
	<li><%= link_to event.name, event_path(event) %></li>
<% end %>
</ul>

app/views/events/menu.html.erb
<%= content_for :header do %>
  <%= link_to_home %>
  <h1>Evento</h1>
<% end %>

<ul data-role="listview" data-inset="true">
  <li data-role="list-divider"><%= current_event.name %></li>
  <li><%= link_to "Información del evento", event_path(current_event) %></li>
  <li><%= link_to "Sesiones propuestas", event_sessions_path(current_event) %></li>
  <li><%= link_to "Agenda", event_agenda_index_path(current_event) %></li>
  <li><%= link_to "Tweets", tweets_event_path(current_event) %></li>
</ul>

app/views/events/new.html.erb
<%= content_for :header do %><h1>Nuevo evento</h1><% end %>
<%= render 'form' %>

app/views/events/show.html.erb
<%= content_for :header do %>
  <%= link_to "", menu_event_path(current_event), 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Información</h1>
  <%= link_to 'Editar', edit_event_path(@event), 'data-role'=>'button' if can? :manage, @event%>
<% end %>

<%= hidden_field(:event, :latitude) %>
<%= hidden_field(:event, :longitude) %>

<h2><%= @event.name %></h2>

<div data-role="collapsible" data-collapsed="false">
  <h3>Datos</h3>
  <% unless @event.starting_at.nil? %>
    Cuando: <%= @event.starting_at.strftime('%d/%m/%Y de %H:%M') + ' a '+ @event.ending_at.strftime('%H:%M')%><br/>
    Donde: <%= @event.where %><br/>
  <% end %>
  Website: <%= href_link(@event.website) %><br/>
  Twitter hashtag: <%= twitter_hashtag_search_link(@event.hashtag) %>
</div>

<div data-role="collapsible" data-collapsed="false">
  <h3>Descripción</h3>
  <%= @event.description %>
</div>

<div data-role="collapsible" data-collapsed="false">
  <h3>Ambientes</h3>
    <% @event.locations.each do |location| %>
      <li><%= location.name %></li>
    <% end %>
</div>

app/views/events/tweets.html.erb
<%= content_for :header do %>
  <%= link_to "", menu_event_path(current_event), 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Tweets</h1>
<% end %>

<ul data-role="listview" data-inset="true">
<% @tweets.each do |tweet| %>
  <li><%= tweet %></li>
<% end %>
</ul>

app/views/events/votes.html.erb
<%= content_for :header do %>
  <%= link_to "", menu_event_path(current_event), 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Votación</h1>
<% end %>

<% if @sessions.empty? %>
  No hay sesiones propuestas.
<% else %>
  <ul data-role="listview" data-inset="true" data-filter="true" data-count-theme="b">
  <% @sessions.each do |session| %>
    <li>
      <%= link_to session.title, event_session_votes_path(current_event, session), :method => :post %>
      <span id="<%= session.id %>" class="ui-li-count">Votos: <%= session.votes_count %></span>
    </li>
  <% end %>
  </ul>
<% end %>