config/routes.rb
Openspace::Application.routes.draw do
  #omniauth
  match "/auth/:provider/callback" => "authentication#create"
  match "/signout" => "authentication#destroy", :as => :signout

  resources :users
  
  resources :events do
    member do
      get 'menu'
      get 'tweets'
      post 'restart_voting'
    end
    
    resources :agenda
    resources :locations
    resources :slots

    resources :sessions do 
      resources :votes
    end
  end
    
  #navigation
  match "/openspace" => "navigation#openspace"
  match "/about" => "navigation#about"
  
  root :to => 'navigation#index'

end

app/models/agenda.rb
# Agenda de un Open Space
class Agenda< ActiveRecord::Base
  attr_accessible :title, :starts, :ends, :event
  belongs_to :event
  has_many :slots
  validates_presence_of :title, :starts, :ends, :event

  # SEO Friendly URLs
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def starts_ends_title
    "#{starts.strftime('%H:%M')} - #{ends.strftime('%H:%M')}: #{title}"
  end

  def starts_ends
    "#{starts.strftime('%H:%M')} - #{ends.strftime('%H:%M')}"
  end

end

app/controllers/agenda_controller.rb
class AgendaController < ApplicationController
  load_and_authorize_resource
  
  def index
    @agenda = Event.find(params[:event_id]).agendas.order(:starts)
  end
  
  def show
    @agenda = Agenda.find(params[:id])
    session[:agenda_id] = params[:id]
  end

  def new
    @agenda = Agenda.new
  end
  
  def edit
    @agenda = Agenda.find(params[:id])
  end

  def create
    @agenda = Agenda.new(params[:agenda])
    @agenda.event = current_event
    if @agenda.save
      redirect_to event_agenda_path(current_event)
    else
      render action: "new"
    end
  end
  
  def update
    @agenda = Agenda.find(params[:id])
    if @agenda.update_attributes(params[:agenda])
      redirect_to event_agenda_path(current_event)
    else
      render action: "edit"
    end
  end

  def destroy
    @agenda = Agenda.find(params[:id])
    @agenda.destroy
    redirect_to event_agenda_index_url(current_event)
  end
  
end

app/views/agenda/_form.html.erb
<%= form_for [current_event, @agenda] do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @agenda.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %><%= f.text_field :title, :class => 'required', :placeholder => 'Título del item de la agenda' %>
  <fieldset data-role="controlgroup" data-type="horizontal">
    <legend>Hora inicio</legend>
    <%= f.time_select :starts %>
  </fieldset>
  
  <fieldset data-role="controlgroup" data-type="horizontal">
    <legend>Hora fin</legend>
    <%= f.time_select :ends %>
  </fieldset>
  
  <fieldset class="ui-grid-a">
      <div class="ui-block-a"><%= f.submit 'Guardar', 'data-icon'=>'check', 'data-theme'=>'b' %></div>
      <div class="ui-block-b"><%= link_to 'Cancelar', event_agenda_index_path(current_event), 'data-role'=>'button', 'data-icon'=>'delete' %></div>
  </fieldset>
<% end %>

<% unless @agenda.new_record? %> 
  <%= button_to "Eliminar", event_agenda_path(current_event, @agenda), :method => :delete, 'data-icon'=>'alert'%>
<% end %>

app/views/agenda/edit.html.erb
<%= content_for :header do %>
  <h1>Agenda</h1>
<% end %>
<%= render 'form' %>

app/views/agenda/index.html.erb
<%= content_for :header do %>
  <%= link_to "", menu_event_path(current_event), 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Agenda</h1>
  <%= link_to "Nuevo", new_event_agenda_path(current_event) if can? :create, Agenda %>
<% end %>

<ul data-role="listview" data-inset="true">
  <% @agenda.each do |item| %>
    <li>
      <%= link_to event_agenda_path(current_event, item) do %>
        <%= item.title %>
        <p class="ui-li-aside"><%= item.starts_ends %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/agenda/new.html.erb
<%= content_for :header do %>
  <h1>Nueva agenda</h1>
<% end %>
<%= render 'form' %>

app/views/agenda/show.html.erb
<%= content_for :header do %>
  <%= link_to "Agenda", event_agenda_index_path(current_event), 'data-icon'=> 'back', 'data-iconpos'=>'notext' %>
  <h1>Detalle de agenda</h1>
<% end %>

<div data-role="controlgroup" data-type="horizontal" data-mini="true">
  <%= link_to "Editar Agenda", edit_event_agenda_path(current_event, @agenda) , 'data-role'=> 'button' if can? :edit, Agenda %>
  <%= link_to "Nuevo slot", new_event_slot_path(current_event), 'data-role'=> 'button' if can? :create, Slot %>
</div>

<ul data-role="listview" data-inset="true">
  <li data-role="list-divider">
    <%= @agenda.title %><p class="ui-li-aside"><%= @agenda.starts_ends %></p>
  </li>
  <% if @agenda.slots.empty? %>
    <li>No hay slots programados</li>
  <% else %>
    <% @agenda.slots.each do |slot| %>
      <li>
        <%= link_to event_slot_path(current_event, slot) do %>
          <h2><%= slot.location.name %></h2>
          <% unless slot.session.nil? %>
            <h3><%= slot.session.title %></h3>
            <p>
              Propuesto por: <%= slot.session.proposed_by %><br />
              Tipo de sesión: <%= slot.session.session_type.capitalize %>
            </p>
          <% end %>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>