config/routes.rb
Openspace::Application.routes.draw do
  #omniauth
  match "/auth/:provider/callback" => "authentication#create"
  match "/signout" => "authentication#destroy", :as => :signout

  resources :users
  
  resources :events do
    member do
      get 'menu'
      get 'tweets'
      post 'restart_voting'
    end
    
    resources :agenda
    resources :locations
    resources :slots

    resources :sessions do 
      resources :votes
    end
  end
    
  #navigation
  match "/openspace" => "navigation#openspace"
  match "/about" => "navigation#about"
  
  root :to => 'navigation#index'

end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController

  def index
    @events = Event.current_events
  end
  
  def about
  end
  
  def openspace
  end

end

app/views/navigation/about.html.erb
<%= content_for :header do %>
  <%= link_to_home %>
  <h1>Acerca de</h1>
<% end %>

<p>Aplicación mobile de manejo de eventos con soporte para Open Spaces.</p>
<a href="https://github.com/lshimokawa/openspace" data-role="button" rel="external">Github repository</a>

app/views/navigation/index.html.erb
<%= content_for :header do %>
  <h1>Open Spaces</h1>
<% end %>

<div data-role="controlgroup" data-type="horizontal" data-mini="true">
  <% unless current_user %>
    <%= link_to "Facebook login", "/auth/facebook", 'data-role'=>'button', :rel => 'external' %>
    <%= link_to "Twitter login", "/auth/twitter", 'data-role'=>'button', :rel => 'external'  %> 
  <% end %>
  <% if current_user %>
    <%= link_to "Logout", signout_path, 'data-role'=> 'button' %>
  <% end %>
</div>

<% if current_user and current_user.admin? %>
  <ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Administración</li>
    <li><%= link_to "Eventos", events_path %></li>
    <li><%= link_to "Usuarios", users_path %></li>
  </ul>
<% end %>

<ul data-role="listview" data-inset="true">
  <li data-role="list-divider">Eventos</li>
  <% @events.each do |event| %>
  	<li>
  	  <%= link_to event.name, menu_event_path(event) %>
  	</li>
  <% end %>
</ul>



<%= content_for :footer do %>
  <div data-role="footer" data-position="fixed">
    <div data-role="navbar">
  		<ul>
  			<li><%= link_to "Sobre los Open Space", openspace_path, "data-icon"=>"star" %></li>
  			<li><%= link_to "Acerca de", about_path, "data-icon"=>"info" %></li>
  		</ul>
  	</div>
	</div>
<% end %>

app/views/navigation/openspace.html.erb
<%= content_for :header do %>
  <%= link_to_home %>
  <h1>Open Space</h1>
<% end %>

<h2>Introducción</h2>
<p>La técnica del Open Space permite conseguir, de un grupo numeroso de personas y en un mínimo tiempo, las mejores ideas alrededor de una o varias grandes materias (“tracks") sobre un gran tema. En un Open Space los asistentes se autoorganizan proponiendo los temas y programando una serie de reuniones que van a tener lugar justo a continuación. Suele durar entre medio día y hasta dos días completos. Las reuniones pueden tener lugar simultáneamente y los asistentes son libres de decidir a qué sesiones quieren asistir y de cambiar de reunión en cualquier momento.</p>

<h2>4 principios</h2>

<h3>Cualquier persona que se presente en una reunión es la persona adecuada</h3>
<p>Cualquier participante en una reunión es correcto simplemente por que se ha preocupado en venir.</p>

<h3>Cualquier cosa que esté sucediendo es la única cosa que podremos llegar a tener</h3>
<p>Estate atento a lo que está pasando ahora, en lugar de preocuparte sobre lo que podría pasar.</p>

<h3>Sea cual sea el momento en que comience, es el momento correcto</h3>
<p>Este principio ayuda a superar la falta de un horario o agendas previo al Open Space y enfatiza la creatividad y la innovación.</p>

<h3>Cuando se acabó, se acabó</h3>
<p>Fomenta que los participantes no desperdicien el tiempo y, por el contrario, que cambien a otro tema cuando una discusión fructífera deja de serlo.</p>

<h2>Ley de los 2 pies</h2>
<p>Si en algún momento sientes que no estás aprendiendo o contribuyendo en nada, usa tus dos pies. Vete a otra reunión donde puedas aprender o contribuir. (Nadie debería estar en una reunión que considera aburrida, sólo las personas que estén genuinamente interesadas en el tema deberían asistir a una reunión).<p/>
<p><br />Fuente: <a href ="http://www.agile-spain.com/que-es-como-hacer-open-space">http://www.agile-spain.com</a></p>